### ISSUE TITLE
Last messages Page implementation

### ISSUE THREAD

**Issue by jaceksupernak** [chingu-voyages/v39-bears-team-11#105]
**__User Story Description__**
As a user
I want to be able to see the last messages page
So I can quickly navigate through my recent chats

**__Steps to Follow__**
Visual:
- [ ] Create mocked last messages data
- [ ] Identify subcomponents 
- [ ] Create semantic html structure
- [ ] Create styling

Data:
Requirements for the Latest Chats  component. After making a get request  to the messages route(/messages/:id), and receiving the array I mentioned above: 
- [ ] - Store chats array received in user state;
- [ ] - Loop over the array objects;
- [ ] - Sort messages of each friend by timestamp;
- [ ] - Return last

**__Additional Considerations__**
[Figma Design](https://www.figma.com/file/vh5P0J7NNAjHwJB4t69weF/Litetalk_Signup-Profile-Chats?node-id=0%3A1)
![Screen Shot 2022-04-27 at 22.15.49.png](https://images.zenhubusercontent.com/620b94f59c5bd35d736f82c0/a3a81284-4a9d-47a4-ab84-18600b892446)
![Screen Shot 2022-04-27 at 22.15.44.png](https://images.zenhubusercontent.com/620b94f59c5bd35d736f82c0/fe98c409-0eef-4214-af79-05361a7f554f)
![Screen Shot 2022-04-27 at 23 07 32](https://user-images.githubusercontent.com/66032213/165639353-d556421e-dfcf-4ed5-bfc8-a73bb2dbba36.png)

**Comment by moody2times** [comment]
@jaceksupernak if this is done, then it should be closed. I think it was closed by #115. I will close it now, if you think it is an error, please reopen it. Thanks
