### ISSUE TITLE
Golang: initialize app

### ISSUE THREAD

**Issue by jaceksupernak** [chingu-voyages/v39-bears-team-11#40]
**__Task Description__**
Initialise Golang App

- [x] Provide instructions on how to run it locally

**__Technical Considerations__**
Include any technical considerations including architecture (e.g. API), required libraries, etc.

**__Additional Considerations__**
Any supplemental information including unresolved questions, links to external resources, screenshots, etc.

**Comment by UfiairENE** [comment]
To initialize app
On your terminal enter
go mod init 
This initializes the application...
To get all dependencies I used enter
go mod tidy
This downloads all dependencies and external libraries used in the repository.
Ensure that your .env file has 
1. PORT= 8080
2. MongoDb url= {{yourmongourl}}
This helps you connect your code to the database, as this is prerequisite for your app to run

To run application enter
go run main.go

**Comment by moody2times** [comment]
Abandoned
