### ISSUE TITLE
Log in my account 

### ISSUE THREAD

**Issue by jaceksupernak** [chingu-voyages/v39-bears-team-11#56]
**__User Story Description__**
As a user
I want to log into my account
So I can so I can start interacting with the app

**__Steps to Follow (optional)__**
- [x] - Write the login router
- [x] - Write the login controller

**__Additional Considerations__**
Any supplemental information including unresolved questions, links to external resources, screenshots, etc.

**Comment by UfiairENE** [comment]
Fixed...
https://github.com/chingu-voyages/v39-bears-team-11be-a/blob/main/controllers/userController.go

The User provides the email and password he used to create the account.
This information is verified and he gets authenticated.
