### ISSUE TITLE
Write the user router

### ISSUE THREAD

**Issue by jaceksupernak** [chingu-voyages/v39-bears-team-11#69]
**__Task Description__**
Write the user router...

**__Technical Considerations__**
Include any technical considerations including architecture (e.g. API), required libraries, etc.

**__Additional Considerations__**
Any supplemental information including unresolved questions, links to external resources, screenshots, etc.

**Comment by uwojeyamudiaga** [comment]
@UfiairENE is asking about the details of this task. Please, @KhadidjaArezki can you reach out to her and provide details?
