### ISSUE TITLE
Add the request logger middleware for backend

### ISSUE THREAD

**Issue by jaceksupernak** [chingu-voyages/v39-bears-team-11#74]
**__Task Description__**
Add the request logger middleware for backend...

**__Technical Considerations__**
Include any technical considerations including architecture (e.g. API), required libraries, etc.

**__Additional Considerations__**
Any supplemental information including unresolved questions, links to external resources, screenshots, etc.

**Comment by uwojeyamudiaga** [comment]
Closed by #99
